# Generated by Django 3.1.8 on 2021-07-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='tite',
            new_name='title',
        ),
    ]
