# Generated by Django 3.1.8 on 2021-07-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_auto_20210709_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='like',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
